
export const motivationalQuotes = [
  "Você é mais forte do que imagina.",
  "Um passo de cada vez ainda é progresso.",
  "Sua jornada é única.",
  "Comece onde está, use o que tem, faça o que puder.",
  "Grandes sonhos exigem coragem.",
  "Acredite no processo.",
  "Não desista agora, você já chegou longe.",
  "O fracasso é só uma curva no caminho.",
  "Tudo tem seu tempo.",
  "O esforço de hoje é o sucesso de amanhã.",
  "Você é capaz de coisas incríveis.",
  "A sua história importa.",
  "Vai com medo mesmo.",
  "Seja teimoso com seus sonhos.",
  "Você é a única pessoa que pode mudar sua vida.",
  "Nada muda se você não mudar.",
  "Tenha fé no seu potencial.",
  "O impossível é só o possível com medo.",
  "Todo dia é uma nova chance.",
  "Faça por você.",
  "Erre, aprenda, recomece.",
  "Respire fundo e continue.",
  "O melhor ainda está por vir.",
  "Não é sobre sorte, é sobre persistência.",
  "Levanta a cabeça, você nasceu pra vencer.",
  "Há força no silêncio e poder na calma.",
  "Pequenas vitórias também contam.",
  "O hoje constrói o amanhã.",
  "Você sobreviveu a 100% dos seus piores dias.",
  "Confie: vai dar certo.",
  "Seja luz, mesmo nos dias nublados.",
  "Cada esforço te aproxima da conquista.",
  "Acredite em você como nunca.",
  "Continue, mesmo sem aplausos.",
  "Seu valor não depende da opinião dos outros.",
  "Tudo começa com um pensamento positivo.",
  "Se não for agora, quando?",
  "Você nasceu para brilhar.",
  "Corra atrás do que te faz vibrar.",
  "Todo mundo começa do zero.",
  "Um dia ruim não define sua vida.",
  "A vida recompensa quem não desiste.",
  "Seja gentil com você.",
  "Não se compare, se inspire.",
  "Você não está sozinho.",
  "Coragem é seguir mesmo com medo.",
  "Siga firme, a estrada se abre.",
  "Sua persistência será recompensada.",
  "Permita-se recomeçar.",
  "Foque no que te faz crescer.",
  "A meta é ser melhor que ontem.",
  "Um sonho sem ação é só ilusão.",
  "Você é maior que qualquer desafio.",
  "O melhor investimento é em você mesmo.",
  "Quem planta esforço, colhe conquistas.",
  "Dias difíceis também passam.",
  "Mude a rota, mas não desista do destino.",
  "Ser constante vale mais do que ser perfeito.",
  "Sua história ainda está sendo escrita.",
  "Acredite, você vai conseguir.",
  "Levanta, sacode a poeira e vai.",
  "Não se subestime.",
  "Tudo o que você precisa está dentro de você.",
  "O medo grita, mas a coragem sussurra mais alto.",
  "Um novo você pode começar agora.",
  "Seja a mudança que você quer viver.",
  "Insista, persista e nunca desista.",
  "Você veio até aqui por um motivo.",
  "Confie nos seus instintos.",
  "Toda dor traz um ensinamento.",
  "Cada manhã é uma nova chance.",
  "Quando faltar motivação, use disciplina.",
  "Ninguém pode tirar o que é seu por direito.",
  "Desistir não é opção.",
  "Um recomeço vale mais que mil desculpas.",
  "Seus sonhos não têm prazo de validade.",
  "Você é mais corajoso do que pensa.",
  "Cada queda é uma chance de levantar mais forte.",
  "Escolha ser positivo.",
  "O que você faz hoje muda tudo.",
  "A vitória começa na mente.",
  "Há beleza no progresso, não só no resultado.",
  "Nunca é tarde para tentar de novo.",
  "Valorize cada conquista, mesmo pequena.",
  "Quem acredita vai mais longe.",
  "O esforço silencioso constrói vitórias barulhentas.",
  "Não se renda ao cansaço.",
  "Todo sacrifício tem um propósito.",
  "Vai com fé, vai com tudo.",
  "Você já tem tudo o que precisa para começar.",
  "Sonhos grandes exigem atitudes grandes.",
  "Faça por você, não pelos outros.",
  "A caminhada é difícil, mas o topo vale a pena.",
  "Duvide das suas dúvidas, não dos seus sonhos.",
  "Recomece quantas vezes for preciso.",
  "Continue — um dia você vai agradecer por não ter parado.",
  "Está tudo bem se ainda não deu certo.",
  "O sucesso é feito de constância.",
  "Todo mundo tem um começo — este é o seu.",
  "Sua vitória está a um passo da sua insistência."
];

export const getRandomMotivationalQuote = (): string => {
  const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
  return motivationalQuotes[randomIndex];
};
