INSERT INTO public.seo_topic_bank (topic, keywords, category, priority) VALUES
('💰 Preço do Cobre por Kg Hoje (2026) — Tabela Atualizada Toda Semana', ARRAY['preço cobre kg 2026','preço cobre hoje','sucata cobre kg'], 'comercial', 10),
('📊 Preço do Alumínio por Kg em 2026 — Latinha, Bloco e Perfil', ARRAY['preço alumínio kg sucata 2026','preço alumínio kg','latinha preço'], 'comercial', 10),
('🔥 Preço do Ferro Velho por Kg Hoje — Tabela Real de 2026', ARRAY['preço ferro velho kg 2026','preço ferro kg','sucata ferro'], 'comercial', 10),
('Cobre Queimado Vale Quanto? Preço Atualizado por Kg em 2026', ARRAY['preço cobre queimado kg','cobre queimado valor','cobre queimado 2026'], 'comercial', 10),
('💸 Tabela de Preços da Reciclagem 2026 — Lista Completa Atualizada', ARRAY['tabela de preços da reciclagem 2026','tabela reciclagem 2026','preços reciclagem'], 'comercial', 10),
('Como Lucrar Mais Vendendo Sucata em 2026 (5 Técnicas Reais)', ARRAY['como vender sucata mais caro','lucrar com sucata','vender sucata 2026'], 'educacional', 9),
('Por Que o Preço da Sucata Muda Toda Semana? Entenda a Variação', ARRAY['variação preço sucata 2026','por que muda preço sucata','oscilação sucata'], 'educacional', 9),
('🚀 Sistema para Ferro Velho em 2026: O Guia Definitivo', ARRAY['sistema para ferro velho','sistema ferro velho 2026','gestão ferro velho'], 'comercial', 10),
('📊 Preço do Latão por Kg 2026 — Tabela por Tipo (Amarelo, Misto, Tubo)', ARRAY['preço latão kg 2026','latão amarelo preço','sucata latão'], 'comercial', 10),
('Software para Ferro Velho: Qual Escolher em 2026 (Comparativo Real)', ARRAY['software para ferro velho','software ferro velho 2026','programa ferro velho'], 'comercial', 10),
('Preço dos Materiais Recicláveis em 2026 — Guia Completo por Tipo', ARRAY['preço materiais recicláveis 2026','valor reciclagem 2026','preço reciclagem'], 'comercial', 10),
('7 Erros que Fazem Você Perder Dinheiro no Ferro Velho (Sem Saber)', ARRAY['erros ferro velho','perder dinheiro sucata','erros sucata'], 'comercial', 9),
('Programa para Ferro Velho Grátis vs Pago: Qual Vale a Pena?', ARRAY['programa ferro velho grátis','sistema gratuito sucata','programa sucata'], 'comercial', 9),
('Preço da Sucata por Kg Hoje — Guia Atualizado de 2026', ARRAY['preço sucata kg hoje','preço sucata 2026','sucata por kg'], 'comercial', 10),
('Controle de Estoque de Sucata: Como Fazer Certo em 2026', ARRAY['controle de estoque sucata','estoque ferro velho','estoque sucata 2026'], 'educacional', 9),
('🔥 Preço do Inox por Kg em 2026 — Tabela Completa (304, 430, Sucata)', ARRAY['preço inox kg 2026','inox 304 preço','sucata inox'], 'comercial', 10),
('Como Calcular o Lucro Real do Seu Ferro Velho (Passo a Passo)', ARRAY['calcular lucro ferro velho','lucro real sucata','lucro ferro velho'], 'educacional', 9),
('Manual vs Sistema no Ferro Velho: Quanto Você Perde em 12 Meses?', ARRAY['manual vs sistema ferro velho','automação ferro velho','sistema vs caderno'], 'comercial', 9),
('📊 Preço da Bateria de Chumbo por Kg em 2026 — Tabela Atualizada', ARRAY['preço bateria chumbo kg 2026','bateria chumbo sucata','preço chumbo'], 'comercial', 10),
('Como Agilizar o Atendimento na Balança do Ferro Velho', ARRAY['agilizar pesagem ferro velho','atendimento balança sucata','balança ferro velho'], 'educacional', 8),
('Fechamento de Caixa no Ferro Velho: Como Fazer Sem Erro', ARRAY['fechamento caixa ferro velho','caixa sucata','fechamento ferro velho'], 'educacional', 8),
('💰 Preço do Bronze por Kg em 2026 — Sucata e Reaproveitamento', ARRAY['preço bronze kg 2026','sucata bronze','bronze valor kg'], 'comercial', 10),
('Como Organizar um Ferro Velho Pequeno do Zero (Guia 2026)', ARRAY['organizar ferro velho pequeno','abrir ferro velho','ferro velho pequeno'], 'educacional', 8),
('Como Evitar Prejuízo Comprando Sucata: Checklist Anti-Fraude', ARRAY['evitar prejuízo sucata','fraude sucata','prejuízo ferro velho'], 'comercial', 9),
('📊 Preço do Motor Elétrico por Kg em 2026 — Tabela Real', ARRAY['preço motor elétrico sucata','motor elétrico sucata kg','sucata motor'], 'comercial', 10),
('Rotina Ideal de um Ferro Velho Organizado (do Abrir ao Fechar)', ARRAY['rotina ferro velho','dia a dia ferro velho','organização ferro velho'], 'educacional', 8),
('Como Precificar Sucata com Base no Mercado Real (Sem Chutar)', ARRAY['como precificar sucata','precificação sucata','preço de compra sucata'], 'comercial', 9),
('🔥 Preço da Sucata Eletrônica em 2026 — Placas, HD e Cabos', ARRAY['preço sucata eletrônica 2026','sucata eletrônica valor','placa eletrônica sucata'], 'comercial', 10),
('CNAE para Ferro Velho: Qual Usar e Como Abrir Empresa em 2026', ARRAY['cnae ferro velho','abrir empresa sucata','cnae sucata'], 'educacional', 8),
('Por Que Todo Ferro Velho Precisa de um Sistema em 2026 (Dados Reais)', ARRAY['sistema ferro velho 2026','automação sucata','digitalizar ferro velho'], 'comercial', 9);