-- Inserir páginas pilar com colunas corretas
INSERT INTO pillar_pages (slug, headline, subheadline, intro_text, features, how_it_works, benefits, testimonials, faq, cta_primary_text, cta_primary_url, status, seo_title, seo_description) VALUES
(
  'sistema-para-deposito-de-reciclagem',
  'Sistema Completo para Depósito de Reciclagem',
  'A solução definitiva para modernizar seu depósito',
  'O XLata é o sistema mais completo do Brasil para gestão de depósitos de reciclagem. Controle compras, vendas, estoque, caixa e muito mais em uma única plataforma.',
  '[{"title": "PDV Especializado", "description": "Ponto de venda desenvolvido para compra e venda de materiais recicláveis.", "icon": "ShoppingCart"}, {"title": "Controle de Caixa", "description": "Abertura, fechamento, sangrias e suprimentos completos.", "icon": "DollarSign"}, {"title": "Gestão de Materiais", "description": "Cadastre materiais com preços de compra e venda.", "icon": "Package"}, {"title": "Relatórios Completos", "description": "Visualize o desempenho do seu negócio.", "icon": "BarChart3"}, {"title": "Recibos Personalizados", "description": "Emita recibos profissionais com sua logo.", "icon": "FileText"}, {"title": "Acesso Online", "description": "Sistema 100% online em qualquer dispositivo.", "icon": "Globe"}]',
  '[{"step": 1, "title": "Crie sua conta", "description": "Cadastre-se gratuitamente."}, {"step": 2, "title": "Configure materiais", "description": "Cadastre os materiais que você trabalha."}, {"step": 3, "title": "Comece a operar", "description": "Abra o caixa e registre operações."}]',
  '["Elimine papel e calculadora", "Reduza erros de pesagem", "Aumente a velocidade de atendimento", "Controle financeiro em tempo real", "Decisões baseadas em dados", "Profissionalize sua operação"]',
  '[]',
  '[{"question": "O sistema funciona offline?", "answer": "O XLata precisa de conexão com internet."}, {"question": "Posso usar no celular?", "answer": "Sim! Sistema responsivo para qualquer dispositivo."}, {"question": "Quanto custa?", "answer": "A partir de R$ 49,90/mês. Teste grátis por 7 dias!"}]',
  'TESTAR GRÁTIS POR 7 DIAS',
  '/register',
  'published',
  'Sistema para Depósito de Reciclagem | XLata',
  'Sistema completo para gestão de depósitos de reciclagem e ferro velhos. Controle compras, vendas, estoque e caixa. Teste grátis!'
),
(
  'sistema-para-ferro-velho',
  'Sistema Profissional para Ferro Velho',
  'Modernize seu ferro velho com tecnologia',
  'Deixe para trás os métodos antigos. O XLata traz tecnologia de ponta para a gestão do seu ferro velho, aumentando produtividade e lucros.',
  '[{"title": "Pesagem Inteligente", "description": "Integração com balanças digitais.", "icon": "Scale"}, {"title": "Cálculo Automático", "description": "Calcula valor baseado no peso e preço.", "icon": "Calculator"}, {"title": "Histórico Completo", "description": "Registro de todas as transações.", "icon": "History"}, {"title": "Gestão de Fornecedores", "description": "Cadastre catadores e fornecedores.", "icon": "Users"}, {"title": "Controle de Margens", "description": "Visualize margens de lucro.", "icon": "TrendingUp"}, {"title": "Suporte Dedicado", "description": "Equipe especializada em reciclagem.", "icon": "Headphones"}]',
  '[{"step": 1, "title": "Abandone a calculadora", "description": "O XLata faz todos os cálculos."}, {"step": 2, "title": "Conecte sua balança", "description": "Integre para pesagens automáticas."}, {"step": 3, "title": "Acompanhe resultados", "description": "Veja seus lucros crescerem."}]',
  '["Atendimento 3x mais rápido", "Zero erros de cálculo", "Controle de fornecedores", "Relatórios gerenciais", "Recibos profissionais", "Backup automático"]',
  '[]',
  '[{"question": "Funciona com minha balança?", "answer": "Compatível com Toledo, Filizola, Urano e outras."}, {"question": "Posso ter vários usuários?", "answer": "Sim! Cadastre funcionários com permissões."}]',
  'COMEÇAR AGORA',
  '/register',
  'published',
  'Sistema para Ferro Velho | Software de Gestão',
  'Software profissional para gestão de ferro velho. Pesagem automática, controle de caixa e relatórios. Aumente seus lucros!'
),
(
  'pdv-para-sucata',
  'PDV Especializado para Compra e Venda de Sucata',
  'O ponto de venda feito para o seu negócio',
  'Um PDV desenvolvido especificamente para depósitos de reciclagem. Registre compras e vendas de sucata com agilidade e precisão.',
  '[{"title": "Interface Intuitiva", "description": "Design para operação rápida.", "icon": "Layout"}, {"title": "Modo Compra e Venda", "description": "Alterne facilmente entre operações.", "icon": "ArrowLeftRight"}, {"title": "Balança Integrada", "description": "Capture peso automaticamente.", "icon": "Scale"}, {"title": "Tara Automática", "description": "Configure tara de recipientes.", "icon": "Minus"}, {"title": "Múltiplos Materiais", "description": "Vários materiais por transação.", "icon": "Layers"}, {"title": "Impressão de Recibos", "description": "Imprima instantaneamente.", "icon": "Printer"}]',
  '[{"step": 1, "title": "Selecione operação", "description": "Escolha Compra ou Venda."}, {"step": 2, "title": "Pese materiais", "description": "Capture peso ou digite."}, {"step": 3, "title": "Finalize e imprima", "description": "Confirme e entregue recibo."}]',
  '["Operação em segundos", "Elimina erros manuais", "Histórico completo", "Recibos profissionais", "Qualquer dispositivo"]',
  '[]',
  '[{"question": "Preciso de impressora especial?", "answer": "Recomendamos térmicas 80mm, mas funciona com qualquer uma."}, {"question": "Posso usar sem balança?", "answer": "Sim! Digite manualmente ou use balança."}]',
  'TESTE GRÁTIS',
  '/register',
  'published',
  'PDV para Sucata e Reciclagem | XLata',
  'PDV especializado para compra e venda de sucata. Integração com balança e recibos automáticos. Experimente grátis!'
),
(
  'controle-de-caixa-reciclagem',
  'Controle de Caixa para Depósitos de Reciclagem',
  'Nunca mais perca dinheiro por falta de controle',
  'Tenha controle total sobre o dinheiro do seu depósito. Abertura, fechamento, sangrias, suprimentos e relatórios detalhados.',
  '[{"title": "Abertura de Caixa", "description": "Inicie o dia com fundo de caixa.", "icon": "DoorOpen"}, {"title": "Registro Automático", "description": "Operações registradas automaticamente.", "icon": "FileCheck"}, {"title": "Sangrias e Suprimentos", "description": "Registre retiradas e adições.", "icon": "ArrowUpDown"}, {"title": "Fechamento de Caixa", "description": "Confira valor esperado x contado.", "icon": "CheckCircle"}, {"title": "Despesas", "description": "Registre despesas operacionais.", "icon": "Receipt"}, {"title": "Relatório Diário", "description": "Visualize movimentações do dia.", "icon": "FileText"}]',
  '[{"step": 1, "title": "Abra o caixa", "description": "Informe valor inicial."}, {"step": 2, "title": "Opere normalmente", "description": "Registre compras e vendas."}, {"step": 3, "title": "Feche e confira", "description": "Conte e compare com sistema."}]',
  '["Identificação de diferenças", "Histórico completo", "Controle por turno", "Relatórios para contador", "Segurança financeira", "Redução de perdas"]',
  '[]',
  '[{"question": "E se houver diferença?", "answer": "Sistema mostra diferença e você pode registrar observação."}, {"question": "Posso ter vários caixas?", "answer": "Sim! Controle cada ponto separadamente."}]',
  'COMEÇAR GRATUITAMENTE',
  '/register',
  'published',
  'Controle de Caixa para Reciclagem | XLata',
  'Sistema de controle de caixa para depósitos de reciclagem. Abertura, fechamento, sangrias e relatórios.'
),
(
  'controle-de-estoque-reciclagem',
  'Controle de Estoque para Materiais Recicláveis',
  'Saiba exatamente o que você tem no depósito',
  'Acompanhe a entrada e saída de materiais em tempo real. Saiba quanto de cada material você tem em estoque.',
  '[{"title": "Estoque Atualizado", "description": "Atualizado a cada compra e venda.", "icon": "Package"}, {"title": "Por Material", "description": "Visualize quantidade de cada tipo.", "icon": "Layers"}, {"title": "Alertas de Volume", "description": "Alertas quando acumular volume.", "icon": "Bell"}, {"title": "Histórico", "description": "Acompanhe entradas e saídas.", "icon": "History"}, {"title": "Custo Médio", "description": "Custo médio de aquisição.", "icon": "Calculator"}, {"title": "Valor do Estoque", "description": "Valor total do estoque.", "icon": "DollarSign"}]',
  '[{"step": 1, "title": "Registre compras", "description": "Compras aumentam estoque."}, {"step": 2, "title": "Acompanhe acúmulo", "description": "Veja estoque crescer."}, {"step": 3, "title": "Registre vendas", "description": "Vendas reduzem estoque."}]',
  '["Visão em tempo real", "Decisões de venda assertivas", "Controle de custo médio", "Histórico completo", "Valor atualizado"]',
  '[]',
  '[{"question": "Estoque é automático?", "answer": "Sim! Atualizado a cada operação."}, {"question": "Posso fazer ajustes?", "answer": "Sim, com registro de motivo."}]',
  'EXPERIMENTAR AGORA',
  '/register',
  'published',
  'Controle de Estoque para Reciclagem | XLata',
  'Sistema de controle de estoque para materiais recicláveis. Acompanhe entradas e saídas em tempo real!'
);