-- Insert 20+ glossary terms for ferro velho niche
INSERT INTO glossary_terms (
  term, slug, short_definition, long_definition, examples,
  seo_title, seo_description, status, allow_indexing, sitemap_priority, sitemap_changefreq
) VALUES 
('Sucata', 'sucata', 
 'Material metálico ou não metálico descartado que pode ser reciclado.',
 'Sucata é qualquer material que foi descartado mas ainda tem valor para reciclagem. Inclui metais (ferro, alumínio, cobre), plásticos, papelão e outros. O ferro velho compra sucata de catadores e fornecedores, separa por tipo e vende para indústrias ou sucateiros maiores.',
 'Latinha de alumínio, panela velha, fios de cobre, peças de ferro de construção, caixas de papelão.',
 'O que é Sucata? Definição e Tipos | Glossário XLata',
 'Sucata é material descartado que pode ser reciclado. Conheça os tipos de sucata e como funciona o mercado de reciclagem.',
 'published', true, 0.5, 'monthly'),

('Tara', 'tara',
 'Peso do recipiente vazio que deve ser descontado da pesagem.',
 'Tara é o peso do recipiente (saco, caixa, carrinho, tambor) que é usado para colocar o material na balança. Para saber o peso líquido do material, é preciso descontar a tara. Exemplo: se o carrinho pesa 5kg e o total na balança é 105kg, o peso líquido é 100kg.',
 'Carrinho de mão pesa 5kg (tara). Big bag vazio pesa 0,5kg. Tambor de plástico pesa 3kg.',
 'O que é Tara na Pesagem? | Glossário XLata',
 'Tara é o peso do recipiente vazio que deve ser descontado. Aprenda como calcular o peso líquido corretamente.',
 'published', true, 0.5, 'monthly'),

('Sangria de Caixa', 'sangria-de-caixa',
 'Retirada parcial de dinheiro do caixa durante o expediente.',
 'Sangria é quando você retira parte do dinheiro do caixa durante o dia, geralmente por segurança (não deixar muito dinheiro acumulado) ou para pagar alguma despesa. A sangria precisa ser registrada para o caixa fechar certo no final do dia.',
 'Retirar R$ 500 do caixa às 15h para pagar combustível. Guardar R$ 1.000 no cofre por segurança.',
 'O que é Sangria de Caixa? | Glossário XLata',
 'Sangria de caixa é a retirada parcial de dinheiro durante o expediente. Entenda quando e como fazer.',
 'published', true, 0.5, 'monthly'),

('Catador', 'catador',
 'Pessoa que coleta materiais recicláveis nas ruas para vender.',
 'Catador é o profissional que coleta materiais recicláveis em residências, comércios e nas ruas. Os catadores são os principais fornecedores de pequenos e médios depósitos de reciclagem. Podem trabalhar de forma autônoma ou em cooperativas.',
 'Catador de latinha, catador de papelão, catador com carrinho de mão, catador de cooperativa.',
 'O que é Catador de Recicláveis? | Glossário XLata',
 'Catador é quem coleta materiais recicláveis para vender. Conheça o trabalho dos catadores na reciclagem.',
 'published', true, 0.5, 'monthly'),

('Prensa', 'prensa',
 'Máquina que compacta materiais para facilitar transporte e armazenamento.',
 'Prensa é um equipamento que comprime materiais como papelão, plástico e latinhas em fardos compactos. Isso reduz o volume para transporte e aumenta o valor na venda (material prensado vale mais que solto). Existem prensas manuais, hidráulicas e elétricas.',
 'Prensa de papelão produz fardos de 100kg. Prensa de latinha compacta alumínio em blocos.',
 'O que é Prensa de Reciclagem? | Glossário XLata',
 'Prensa é a máquina que compacta materiais recicláveis em fardos. Entenda os tipos e benefícios.',
 'published', true, 0.5, 'monthly'),

('Balança Digital', 'balanca-digital',
 'Equipamento eletrônico para pesar materiais com precisão.',
 'A balança digital é essencial no ferro velho para pesar os materiais comprados e vendidos. Oferece leitura precisa e rápida do peso. Existem vários modelos: de plataforma (para grandes volumes), de bancada (para pequenos volumes) e industriais (capacidade de toneladas).',
 'Balança de plataforma 500kg para pesar carrinhos. Balança de bancada 30kg para cobre e alumínio.',
 'Balança Digital para Ferro Velho | Glossário XLata',
 'Balança digital é essencial para pesar materiais no ferro velho. Conheça os tipos e como escolher.',
 'published', true, 0.5, 'monthly'),

('Fardo', 'fardo',
 'Material compactado em formato retangular para facilitar transporte.',
 'Fardo é o bloco compactado de material reciclável, geralmente papelão, plástico ou latinhas. O fardo facilita o transporte (ocupa menos espaço) e aumenta o valor de venda. O peso varia: fardos de papelão costumam ter 100-200kg, de latinha 50-100kg.',
 'Fardo de papelão de 150kg. Fardo de PET de 80kg. Fardo de alumínio de 50kg.',
 'O que é Fardo de Reciclagem? | Glossário XLata',
 'Fardo é o material compactado em bloco. Aprenda como fazer fardos e aumentar o valor de venda.',
 'published', true, 0.5, 'monthly'),

('Cobre Misto', 'cobre-misto',
 'Cobre misturado com outros materiais ou de diferentes origens.',
 'Cobre misto é aquele que vem misturado: fios finos com fios grossos, cobre com restos de isolamento, peças de diferentes purezas. Por ter qualidade variada, vale menos que o cobre primeira (mais puro). É importante separar para conseguir melhores preços.',
 'Fios de cobre com capa plástica. Mistura de cobre de instalação e de motor. Peças com solda.',
 'O que é Cobre Misto? | Glossário XLata',
 'Cobre misto é cobre de diferentes origens misturado. Entenda a diferença de preço e como separar.',
 'published', true, 0.5, 'monthly'),

('Cobre Primeira', 'cobre-primeira',
 'Cobre de alta pureza, sem mistura ou contaminação.',
 'Cobre primeira (ou cobre 1ª) é o mais puro e valioso. São fios grossos, barras ou chapas sem soldas, sem verniz e sem outros metais misturados. Por ter alta pureza, vale significativamente mais que o cobre misto. A diferença pode chegar a R$ 15-20 por kg.',
 'Barra de cobre puro. Fio de cobre grosso sem capa. Chapa de cobre sem solda.',
 'O que é Cobre Primeira? | Glossário XLata',
 'Cobre primeira é o mais puro e valioso. Veja como identificar e quanto vale.',
 'published', true, 0.5, 'monthly'),

('Alumínio Lata', 'aluminio-lata',
 'Alumínio proveniente de latas de bebidas (refrigerante, cerveja, etc).',
 'Alumínio lata é o tipo mais comum e um dos mais valiosos de alumínio. Vem das latas de refrigerante, cerveja, suco e energético. Tem alta pureza e é fácil de reciclar. Muito procurado por catadores pelo volume disponível e bom preço.',
 'Latinha de Coca-Cola, latinha de cerveja, latinha de energético.',
 'O que é Alumínio Lata? | Glossário XLata',
 'Alumínio lata é o de latinhas de bebida. Conheça o preço e por que é tão valorizado.',
 'published', true, 0.5, 'monthly'),

('Alumínio Panela', 'aluminio-panela',
 'Alumínio fundido proveniente de utensílios de cozinha.',
 'Alumínio panela (ou alumínio fundido) vem de utensílios como panelas, frigideiras e formas. Tem valor menor que o alumínio lata porque contém ligas metálicas e pode ter outros materiais (cabos, parafusos). Precisa ser separado de peças de plástico e ferro.',
 'Panela de alumínio, frigideira, forma de bolo, chaleira.',
 'O que é Alumínio Panela? | Glossário XLata',
 'Alumínio panela vem de utensílios de cozinha. Veja o preço e como identificar.',
 'published', true, 0.5, 'monthly'),

('PDV', 'pdv',
 'Ponto de Venda: local ou sistema onde transações são registradas.',
 'PDV (Ponto de Venda) no contexto de ferro velho se refere ao sistema usado para registrar compras de materiais. É onde você seleciona o material, digita o peso e registra a transação. Um bom PDV calcula automaticamente e imprime recibo.',
 'PDV no celular para registrar compras. PDV no computador do balcão.',
 'O que é PDV? | Glossário XLata',
 'PDV significa Ponto de Venda. No ferro velho, é o sistema para registrar compras de materiais.',
 'published', true, 0.5, 'monthly'),

('Ferro Velho', 'ferro-velho',
 'Estabelecimento que compra e vende materiais para reciclagem.',
 'Ferro velho é o nome popular para depósito de reciclagem. É o local onde catadores e fornecedores vendem materiais (alumínio, cobre, ferro, papelão, etc.) e onde esses materiais são separados, pesados e posteriormente vendidos para sucateiros maiores ou indústrias.',
 'Ferro velho de esquina, depósito de reciclagem, sucateiro.',
 'O que é Ferro Velho? | Glossário XLata',
 'Ferro velho é o estabelecimento que compra e vende materiais recicláveis. Entenda como funciona.',
 'published', true, 0.5, 'monthly'),

('Latão', 'latao',
 'Liga metálica de cobre e zinco, encontrada em torneiras e válvulas.',
 'Latão é uma liga de cobre e zinco, de cor amarelada dourada. Encontrado em torneiras, válvulas, registros, conexões de água e peças decorativas. Tem bom valor de reciclagem, intermediário entre cobre e alumínio. Não confundir com bronze.',
 'Torneira antiga, registro de água, válvula de gás, puxador de porta.',
 'O que é Latão? | Glossário XLata',
 'Latão é liga de cobre e zinco. Encontrado em torneiras e válvulas. Conheça o valor na reciclagem.',
 'published', true, 0.5, 'monthly'),

('Inox', 'inox',
 'Aço inoxidável: liga resistente a corrosão, encontrada em pias e utensílios.',
 'Inox (aço inoxidável) é uma liga de ferro, cromo e níquel que não enferruja. Encontrado em pias, cubas, panelas, talheres e equipamentos industriais. Tem bom valor na reciclagem. Pode ser identificado pelo teste do ímã: inox de qualidade não gruda.',
 'Pia de cozinha, cuba de inox, panela de inox, tacho industrial.',
 'O que é Inox na Reciclagem? | Glossário XLata',
 'Inox é aço inoxidável resistente a corrosão. Veja como identificar e o valor na reciclagem.',
 'published', true, 0.5, 'monthly'),

('PET', 'pet',
 'Plástico de garrafas de refrigerante e água mineral.',
 'PET (polietileno tereftalato) é o plástico transparente usado em garrafas de refrigerante, água mineral, sucos e produtos de limpeza. É um dos plásticos mais reciclados. Precisa estar limpo e de preferência separado por cor (transparente vale mais).',
 'Garrafa de refrigerante, garrafa de água, frasco de amaciante.',
 'O que é PET? | Glossário XLata',
 'PET é o plástico de garrafas. Saiba como reciclar e o valor no mercado.',
 'published', true, 0.5, 'monthly'),

('Big Bag', 'big-bag',
 'Saco grande de ráfia usado para armazenar e transportar materiais.',
 'Big bag é um saco grande feito de ráfia (material trançado), usado para armazenar e transportar materiais em grandes volumes. Facilita a organização do depósito e o carregamento para venda. Capacidade típica: 500kg a 1500kg dependendo do material.',
 'Big bag para papelão, big bag para plástico, big bag para PET.',
 'O que é Big Bag? | Glossário XLata',
 'Big bag é saco grande para armazenar materiais recicláveis. Conheça tamanhos e usos.',
 'published', true, 0.5, 'monthly'),

('Material de Segunda', 'material-de-segunda',
 'Material de qualidade inferior que vale menos na reciclagem.',
 'Material de segunda é aquele que tem qualidade inferior: sujo, misturado, danificado ou contaminado. Vale menos que o material limpo e bem separado. Exemplos: alumínio com tinta, cobre com solda, papelão molhado.',
 'Alumínio pintado, cobre com verniz, papelão com óleo.',
 'O que é Material de Segunda? | Glossário XLata',
 'Material de segunda é de qualidade inferior na reciclagem. Entenda a diferença de preço.',
 'published', true, 0.5, 'monthly'),

('Fechamento de Caixa', 'fechamento-de-caixa',
 'Conferência do dinheiro no final do expediente.',
 'Fechamento de caixa é o processo de contar o dinheiro no final do dia e comparar com o que deveria ter segundo os registros. Se o valor real for diferente, indica erro em algum lançamento ou problema mais sério. É fundamental fazer o fechamento diariamente.',
 'Fechar o caixa às 18h. Conferir notas e moedas. Comparar com o sistema.',
 'O que é Fechamento de Caixa? | Glossário XLata',
 'Fechamento de caixa é a conferência do dinheiro no fim do dia. Aprenda como fazer corretamente.',
 'published', true, 0.5, 'monthly'),

('Abertura de Caixa', 'abertura-de-caixa',
 'Registro do saldo inicial em dinheiro no início do expediente.',
 'Abertura de caixa é registrar quanto dinheiro tem no caixa no início do dia. Esse valor é o ponto de partida para calcular entradas e saídas. Sem abertura correta, o fechamento não vai bater. Faça sempre antes de começar a operar.',
 'Abrir o caixa com R$ 500. Registrar saldo inicial. Conferir notas.',
 'O que é Abertura de Caixa? | Glossário XLata',
 'Abertura de caixa é registrar o saldo inicial do dia. Fundamental para controle financeiro.',
 'published', true, 0.5, 'monthly'),

('Recibo de Compra', 'recibo-de-compra',
 'Comprovante dado ao fornecedor após a compra de material.',
 'Recibo de compra é o comprovante que o ferro velho dá ao fornecedor após comprar material. Deve conter: data, material, peso, preço por kg, valor total e identificação do depósito. Dá credibilidade ao negócio e evita discussões posteriores.',
 'Recibo com data, peso e valor. Comprovante para catador. Nota de compra.',
 'O que é Recibo de Compra? | Glossário XLata',
 'Recibo de compra é o comprovante dado ao fornecedor. Veja o que precisa conter.',
 'published', true, 0.5, 'monthly')

ON CONFLICT (slug) DO UPDATE SET
  term = EXCLUDED.term,
  short_definition = EXCLUDED.short_definition,
  long_definition = EXCLUDED.long_definition,
  examples = EXCLUDED.examples,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  status = EXCLUDED.status,
  allow_indexing = EXCLUDED.allow_indexing,
  sitemap_priority = EXCLUDED.sitemap_priority,
  sitemap_changefreq = EXCLUDED.sitemap_changefreq,
  updated_at = now();