-- Inserir termos de glossário
INSERT INTO glossary_terms (term, slug, short_definition, long_definition, examples, status, seo_title, seo_description) VALUES
('Sucata', 'sucata', 'Material metálico descartado que pode ser reciclado e reutilizado na indústria.', 'Sucata é o termo usado para designar materiais metálicos que foram descartados, mas que ainda possuem valor comercial por poderem ser reciclados. Inclui ferro, aço, alumínio, cobre e outros metais.', 'Ferro velho de construção, latarias de carro, panelas velhas, fios de cobre.', 'published', 'O que é Sucata? | Glossário XLata', 'Entenda o que é sucata e como ela é comercializada em depósitos de reciclagem.'),
('Ferro Velho', 'ferro-velho', 'Estabelecimento comercial que compra e vende materiais metálicos usados para reciclagem.', 'Ferro velho é o nome popular dado aos depósitos que comercializam materiais metálicos usados. Esses estabelecimentos compram sucata de catadores e particulares e vendem para indústrias recicladoras.', 'Depósito de reciclagem, sucateiro, deposito de ferro.', 'published', 'O que é Ferro Velho? | Glossário XLata', 'Saiba o que é ferro velho e como funciona esse tipo de negócio de reciclagem.'),
('PDV', 'pdv-ponto-de-venda', 'Ponto de Venda - sistema utilizado para registrar transações comerciais de compra e venda.', 'PDV significa Ponto de Venda e é o sistema usado para registrar operações comerciais. Em depósitos de reciclagem, o PDV registra compras de materiais de catadores e vendas para indústrias.', 'Sistema XLata, caixa registradora, terminal de vendas.', 'published', 'O que é PDV? | Glossário XLata', 'Entenda o que é PDV (Ponto de Venda) e como ele funciona em depósitos de reciclagem.'),
('Tara', 'tara-peso', 'Peso do recipiente ou veículo que deve ser descontado na pesagem de materiais.', 'Tara é o peso do recipiente, embalagem ou veículo que contém o material a ser pesado. Esse peso deve ser descontado para obter o peso líquido do material. Em depósitos, é comum tarar carrinhos de catadores.', 'Peso do carrinho de catador, peso da caçamba do caminhão.', 'published', 'O que é Tara? | Glossário XLata', 'Entenda o conceito de tara na pesagem de materiais recicláveis.'),
('Sangria de Caixa', 'sangria-de-caixa', 'Retirada de dinheiro do caixa durante o expediente para depósito ou segurança.', 'Sangria é a operação de retirar parte do dinheiro do caixa durante o expediente. É feita para depositar no banco, guardar em cofre ou por segurança quando há muito dinheiro acumulado.', 'Retirada de R$ 500 para depositar no banco, transferência para cofre.', 'published', 'O que é Sangria de Caixa? | Glossário XLata', 'Saiba o que é sangria de caixa e quando fazer em seu depósito de reciclagem.'),
('Balança Digital', 'balanca-digital', 'Equipamento eletrônico para pesagem precisa de materiais recicláveis.', 'Balança digital é o equipamento usado para pesar materiais com precisão. Pode ser de bancada, plataforma ou rodoviária, dependendo do volume de material. Algumas podem ser integradas a sistemas de gestão.', 'Balança Toledo, Filizola, Urano, balança de plataforma.', 'published', 'O que é Balança Digital? | Glossário XLata', 'Conheça os tipos de balanças digitais para depósitos de reciclagem.'),
('Alumínio Latinha', 'aluminio-latinha', 'Latas de bebidas feitas de alumínio, um dos materiais mais valiosos na reciclagem.', 'Alumínio latinha refere-se às latas de bebidas (refrigerante, cerveja) feitas de alumínio. É um dos materiais mais valiosos na reciclagem devido à facilidade de reciclagem e alta demanda da indústria.', 'Latas de refrigerante, latas de cerveja, latas de energético.', 'published', 'O que é Alumínio Latinha? | Glossário XLata', 'Saiba sobre o alumínio de latinhas e seu valor no mercado de reciclagem.'),
('Cobre', 'cobre', 'Metal não-ferroso de alto valor utilizado em instalações elétricas e hidráulicas.', 'O cobre é um metal não-ferroso de cor avermelhada, muito valorizado na reciclagem. É usado em fios elétricos, tubulações e componentes eletrônicos. Existem tipos: cobre vermelho (puro) e cobre misto.', 'Fios elétricos, tubos de ar condicionado, bobinas de motor.', 'published', 'O que é Cobre? | Glossário XLata', 'Conheça o cobre e sua importância na reciclagem de metais.'),
('Papelão', 'papelao', 'Material de papel em camadas usado em embalagens, reciclável após separação.', 'Papelão é o material feito de papel em múltiplas camadas, usado principalmente em caixas e embalagens. Na reciclagem, deve estar limpo e seco. O papelão ondulado é o mais comum e valorizado.', 'Caixas de produtos, embalagens de eletrodomésticos.', 'published', 'O que é Papelão? | Glossário XLata', 'Entenda sobre o papelão reciclável e seu valor no mercado.'),
('PET', 'pet-plastico', 'Plástico transparente usado em garrafas, altamente reciclável.', 'PET (Politereftalato de Etileno) é um tipo de plástico transparente usado principalmente em garrafas de bebidas. É altamente reciclável e tem boa demanda no mercado de reciclagem.', 'Garrafas de refrigerante, garrafas de água, embalagens.', 'published', 'O que é PET? | Glossário XLata', 'Saiba o que é PET e como é reciclado em depósitos.'),
('Catador', 'catador', 'Profissional que coleta materiais recicláveis para venda em depósitos.', 'Catador é o profissional que coleta materiais recicláveis nas ruas, residências e empresas. Eles são fornecedores importantes para depósitos de reciclagem e desempenham papel fundamental na cadeia de reciclagem.', 'Catador de latinha, catador de papelão, carrinheiro.', 'published', 'O que é Catador? | Glossário XLata', 'Conheça a profissão de catador e sua importância na reciclagem.'),
('Fluxo de Caixa', 'fluxo-de-caixa', 'Movimento de entrada e saída de dinheiro em um negócio.', 'Fluxo de caixa é o registro de todas as entradas e saídas de dinheiro do negócio. Permite visualizar a saúde financeira da empresa e tomar decisões sobre compras, vendas e investimentos.', 'Entradas: vendas. Saídas: compras, despesas, sangrias.', 'published', 'O que é Fluxo de Caixa? | Glossário XLata', 'Entenda o fluxo de caixa e sua importância na gestão de depósitos.'),
('Margem de Lucro', 'margem-de-lucro', 'Diferença percentual entre o preço de venda e o custo de aquisição.', 'Margem de lucro é a diferença entre o preço de venda e o custo de aquisição de um material, expressa em percentual. Uma margem saudável garante a sustentabilidade do negócio.', 'Comprou ferro a R$ 0,50/kg e vendeu a R$ 0,70/kg = 40% de margem.', 'published', 'O que é Margem de Lucro? | Glossário XLata', 'Saiba calcular e otimizar a margem de lucro em reciclagem.'),
('Reciclagem Industrial', 'reciclagem-industrial', 'Processo de transformação de materiais usados em novos produtos pela indústria.', 'Reciclagem industrial é o processo realizado por indústrias para transformar materiais usados em matéria-prima para novos produtos. Depósitos fornecem materiais para essas indústrias.', 'Fundição de alumínio, fabricação de papel reciclado.', 'published', 'O que é Reciclagem Industrial? | Glossário XLata', 'Entenda como funciona a reciclagem industrial de materiais.');
